# Generated by Django 2.2.5 on 2019-10-02 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20190929_0002'),
        ('player', '0002_auto_20191001_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chess.ChessOpening'),
        ),
    ]
