# Generated by Django 2.2.5 on 2019-10-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_opening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='favourite_open',
        ),
    ]
