# Generated by Django 2.2.5 on 2019-10-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_remove_player_favourite_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='averate_rate',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1, null=True),
        ),
    ]
