# Generated by Django 2.2.5 on 2019-10-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_player_averate_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='averate_rate',
        ),
    ]
