# Generated by Django 2.2.5 on 2019-10-29 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_playerrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerrate',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
