# Generated by Django 2.2.5 on 2019-09-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20190908_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
