# Generated by Django 2.2.5 on 2019-10-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20190929_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessopening',
            name='algebraic_notation',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AlterField(
            model_name='chessopening',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chessopening',
            name='epd',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
