# Generated by Django 2.2.5 on 2019-10-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_auto_20191016_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessopening',
            name='algebraic_notation',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='chessopening',
            name='epd',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
