# Generated by Django 2.2.5 on 2019-10-18 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0004_remove_player_favourite_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
