# Generated by Django 2.2.5 on 2019-10-18 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20191018_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
