# Generated by Django 2.2.5 on 2019-10-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20191018_2355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerRate',
        ),
    ]
